sentiment_words = {
    "positive": [
        "happy", "joyful", "excited", "delighted", "thrilled", "grateful",
        "blessed", "wonderful", "amazing", "fantastic", "excellent", "great",
        "good", "nice", "kind", "loving", "caring", "friendly", "supportive",
        "helpful", "generous", "optimistic", "confident", "strong", "brave",
        "successful", "prosperous", "healthy", "beautiful", "charming",
        "brilliant", "intelligent", "wise", "creative", "innovative",
        "peaceful", "calm", "serene", "content", "satisfied", "fulfilled",
        "vibrant", "lively", "energetic", "passionate", "determined",
        "resilient", "grateful", "appreciative", "positive", "uplifting",
        "encouraging", "inspiring", "motivating", "empowering", "fabulous",
        "outstanding", "remarkable", "terrific", "splendid", "superb",
        "awesome", "lovely", "adorable", "sweet", "cute", "precious",
        "innocent", "pure", "honest", "truthful", "loyal", "faithful",
        "reliable", "dependable", "trustworthy", "respectful", "polite",
        "courteous", "gentle", "compassionate", "forgiving", "understanding",
        "accepting", "tolerant", "patient", "wise", "thoughtful", "insightful",
        "clever", "smart", "talented", "gifted", "skillful", "expert",
        "professional", "efficient", "effective", "productive", "valuable",
        "worthwhile", "meaningful", "significant", "important", "essential",
        "vital", "crucial", "fundamental", "positive", "good", "great",
        "best", "finest", "top", "leading", "foremost", "premier", "choice",
        "select", "superior", "excellent", "wonderful", "amazing", "fantastic",
        "unbelievable", "incredible", "remarkable", "extraordinary", "sensational",
        "stunning", "impressive", "magnificent", "glorious", "splendid",
        "sumptuous", "lavish", "opulent", "grand", "majestic", "palatial",
        "regal", "royal", "princely", "noble", "aristocratic", "elegant",
        "refined", "cultured", "sophisticated", "tasteful", "artistic",
        "creative", "imaginative", "visionary", "ingenious", "innovative",
        "original", "unique", "distinctive", "special", "rare", "uncommon",
        "exceptional", "outstanding", "peerless", "unrivaled", "matchless",
        "incomparable", "unsurpassed", "unequaled", "unprecedented", "perfect",
        "flawless", "immaculate", "spotless", "unblemished", "pristine",
        "pure", "unadulterated", "genuine", "authentic", "real", "true",
        "factual", "accurate", "correct", "right", "proper", "appropriate",
        "suitable", "fitting", "apt", "relevant", "pertinent", "applicable",
        "valid", "sound", "solid", "strong", "robust", "secure", "safe",
        "protected", "guarded", "preserved", "maintained", "conserved",
        "sustained", "developed", "enhanced", "improved", "advanced",
        "progressed", "flourished", "thrived", "prospered", "succeeded",
        "achieved", "attained", "accomplished", "completed", "finished",
        "done", "ready", "prepared", "equipped", "capable", "competent",
        "qualified", "skilled", "experienced", "knowledgeable", "informed",
        "educated", "learned", "wise", "shrewd", "astute", "perceptive",
        "discerning", "insightful", "intuitive", "brilliant", "genius",
        "gifted", "talented", "creative", "imaginative", "visionary",
        "ingenious", "innovative", "original", "unique", "distinctive",
        "special", "rare", "uncommon", "exceptional", "outstanding",
        "peerless", "unrivaled", "matchless", "incomparable", "unsurpassed",
        "unequaled", "unprecedented", "perfect", "flawless", "immaculate",
        "spotless", "unblemished", "pristine", "pure", "unadulterated",
        "genuine", "authentic", "real", "true", "factual", "accurate",
        "correct", "right", "proper", "appropriate", "suitable", "fitting",
        "apt", "relevant", "pertinent", "applicable", "valid", "sound",
        "solid", "strong", "robust", "secure", "safe", "protected", "guarded",
        "preserved", "maintained", "conserved", "sustained", "developed",
        "enhanced", "improved", "advanced", "progressed", "flourished",
        "thrived", "prospered", "succeeded", "achieved", "attained",
        "accomplished", "completed", "finished", "done", "ready", "prepared",
        "equipped", "capable", "competent", "qualified", "skilled",
        "experienced", "knowledgeable", "informed", "educated", "learned",
        "wise", "shrewd", "astute", "perceptive", "discerning", "insightful",
        "intuitive", "brilliant", "genius"  # ... and many more
    ],
    "negative": [
        "sad", "unhappy", "miserable", "depressed", "gloomy", "sorrowful",
        "mournful", "tragic", "awful", "terrible", "horrible", "dreadful",
        "bad", "evil", "wicked", "cruel", "mean", "unkind", "unfriendly",
        "hostile", "aggressive", "violent", "angry", "furious", "enraged",
        "frustrated", "annoyed", "irritated", "bothered", "upset", "mad",
        "disappointed", "dissatisfied", "frustrated", "stressed", "anxious",
        "nervous", "scared", "afraid", "terrified", "horrified", "panicked",
        "guilty", "ashamed", "embarrassed", "humiliated", "regretful",
        "remorseful", "apologetic", "sorry", "lonely", "isolated", "alone",
        "abandoned", "rejected", "unloved", "unwanted", "worthless",
        "hopeless", "pessimistic", "cynical", "skeptical", "doubtful",
        "uncertain", "insecure", "vulnerable", "weak", "helpless", "powerless",
        "defeated", "failed", "lost", "broken", "damaged", "hurt", "injured",
        "sick", "ill", "diseased", "unhealthy", "tired", "exhausted", "fatigued",
        "bored", "apathetic", "indifferent", "uninterested", "lazy", "idle",
        "sluggish", "slow", "unproductive", "inefficient", "ineffective",
        "useless", "worthless", "meaningless", "insignificant", "trivial",
        "unimportant", "irrelevant", "inappropriate", "unsuitable", "unfitting",
        "inapt", "invalid", "unsound", "weak", "fragile", "vulnerable",
        "insecure", "unsafe", "unprotected", "unguarded", "neglected", "ignored",
        "forgotten", "lost", "misplaced", "damaged", "broken", "ruined",
        "destroyed", "demolished", "shattered", "crushed", "defeated",
        "vanquished", "conquered", "subdued", "overwhelmed", "oppressed",
        "exploited", "abused", "mistreated", "maltreated", "neglected",
        "abandoned", "rejected", "unloved", "unwanted", "worthless",
        "hopeless", "pessimistic", "cynical", "skeptical", "doubtful",
        "uncertain", "insecure", "vulnerable", "weak", "helpless", "powerless",
        "defeated", "failed", "lost", "broken", "damaged", "hurt", "injured",
        "sick", "ill", "diseased", "unhealthy", "tired", "exhaust"]}